### PR TITLE
Use png instead of svg

### PR DESCRIPTION
**Pull request by AristoChen**
Hi, I found that if using github app(on Android) to browse the repo, the logo will not be able to be displayed properly, so I convert the `logo.svg` to `logo.png`

Using `logo.svg`:

Using `logo.png`:

Same issue on other repo using `logo.svg`, will create PR for other repo if this PR is merged.

### CODE REVIEW

**Comment by mre** [comment]
Hey @AristoChen. Just now saw your PR. Sorry for the late response. Turns out I was not watching this repo for changes...
Anyway, thanks for the fix. I just wonder how it works because I can't see any png in the repository. Is it somehow auto-generated by Github!?

**Comment by AristoChen** [comment]
No worry, 

>  I can't see any png in the repository

You mean this `logo.png`?
image

**Comment by mre** [comment]
Oh alright, my bad. LGTM. I just wonder why the CI is suddenly failing.

**Comment by AristoChen** [comment]
I am not familiar with github CI flow, Is there anything that I did wrong? Or any suggestion how to fix it?

**Comment by mre** [comment]
No clue. You certainly didn't do anything wrong. Let's just merge it and see what happens. 😆

**Pull request merged**
