### PR TITLE
Add Carousel component

### LINKED ISSUE #15: Add gallery for screenshots/videos
For many tools we have more than one visual resource now. We should present them in a more appealing way. E.g. with a simple lightweight gallery or a lightbox.

### PR DESCRIPTION
**Pull request by paulrrdiaz**
Close #15

### CODE REVIEW

**Comment by mre** [comment]
Looks like the credentials don't work for pull requests from external origins. 
The code itself looks fine. Thanks!

I wonder if we could have small thumbnails below the slider as well, similar to 
https://github.com/YIZHUANG/react-multi-carousel/pull/45 and https://www.freakyjolly.com/react-slick-carousel-with-custom-navigation-and-lazy-loaded-images-in-slider/

image

On clicking on a thumbnail, the slider would jump to the item.
What do you think?

**Comment by paulrrdiaz** [comment]
Doable, but you need to add the thumb manually (cuz video/other content)
is that ok?

**Comment by jakubsacha** [comment]
This looks very nice!

two options come co my mind:
* use some pre-made static picture for the video thumbs - this feels like the easiest start.
* use some free api out there that can generate video thumbnails - I sadly don't know any. For youtube videos probably that can be fetched from the youtube api.

Do you think we should merge it like it is and tackle thumbnails in the separate PR?

Thanks for a great contribution :tada:

**Comment by mre** [comment]
> Do you think we should merge it like it is and tackle thumbnails in the separate PR?

Yeah. PR looks fine already and it's a great improvement, so let's merge.
Will create a separate issue for the thumbnails for anyone that wants to pick it up.

Thanks so much for the contribution @paulrrdiaz. High quality work. 😍

**Pull request merged**
